name: Build Samah APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: إعداد Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: إعداد Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: بناء APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: Samah-debug-apk
          path: app/build/outputs/apk/debug/*.apk
